--- 
Title: herald_example
Type: test
Protocol: http
Version: "0.1"
Domain: duckbunny
Method: POST
Parameters: 
  - 
    DataType: "map[string]string"
    Description: "My first test parameter"
    Key: testparam1
    Required: false
    Type: json
  - 
    DataType: string
    Description: "My second test parameter"
    Key: testparam2
    Required: true
    Type: header
Private: false
Requires: 
  - 
    Domain: duckbunny
    Title: service2
    Version: "0.1"
  - 
    Domain: duckbunny
    Title: service3
    Version: "0.1"
Response: 
  DataType: "map[string]string"
  Type: googlejson
Flags: 
  - 
    Key: "test"
    Env: "TESTVAR"
    Description: "This is a test flag."
    Required: true
